---
- name: Linux Module running
  hosts: tests
  become: yes
  gather_facts: false
  tasks:
    - name: create a file with some specific acl
      file:
         path: /usr/local/script.py
         state: touch
         owner: root
         group: sudo
         mode: 0755

    - name: copy file from within a remote host
      copy:
        src: /usr/local/script.py
        dest: /home/install/script.py
        remote_src: yes
        owner: install
        group: sudo
        mode: 0755

    - name: download an ansible archive to remote hosts
      get_url:
        url: https://github.com/ansible/ansible/archive/v2.9.1.tar.gz
        dest: /usr/local/ansible_v2.9.1.tar.gz
        mode: 0777

    - name: extract an archive into remote hosts
      unarchive:
        src: /usr/local/ansible_v2.9.1.tar.gz
        dest: /home/install/
        owner: install
        group: sudo
        mode: 0755

