- hosts: all
  order: sorted
  gather_facts: False
  tasks:
  - name: Copy ansible inventory file to client
    copy: src=/etc/ansible/hosts dest=/root/hosts
            owner=root group=root mode=0644